[workspace]
resolver = "2"
members = ["bootstrap",
    "example",
    "moonwalk"
]

[profile.release]
opt-level = 3
lto = true
target-cpu = "native"
debug = false

[workspace.dependencies]
moonwalk = { path = "./moonwalk" }
